resources:
  - name: breakfastly
    type: time
    source: {interval: 1m}

  - name: our-git-repo
    type: git
    source:
      uri: https://github.com/pivotalleye/yarg.git

jobs:
  - name: breakfast-test-run
    plan:
      - get: our-git-repo
        trigger: true
      - get: breakfastly
        trigger: true
      - task: dummy-task
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ubuntu}
          run:
            path: exit
            args: [1]